### ISSUE TITLE
This isint working!!

### ISSUE THREAD

**Issue by Qasim-AJ** [openfoodfacts/openfoodfacts-java-demo#1]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project micronaut-openfoodfacts-java-wrapper-demo: Fatal error compiling: invalid target release: 11 -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by toudidel** [comment]
_class file has wrong version 55.0, should be 52.0_ and _Fatal error compiling: invalid target release: 11_ means you try to compile your project with Java compiler version 8 instead of 11. Try to use Java 11 or newer.

**Comment by Qasim-AJ** [comment]
Thanks Alot for your rapid response. Bascially i'm new to this and im trying to figure things out.
It will be very helpful if you could provide a proper walkthrough to use this api.
Actually this is my first ever interaction with APIs.

**Comment by toudidel** [comment]
Only one requirement is a proper Java version which should be 11 or newer in this case.
